import './globals.css'
import type { Metadata } from 'next'
import React from 'react'

import { Navigation } from '../components/Navigation'
import { font } from './front'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head>
        <title>My first app with Next 13</title>
      </head>

      <body className={font.className}>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
